### ISSUE TITLE
Get error `An invalid parameter was given.` 

### ISSUE THREAD

**Issue by theggs** [TuringSoftware/CrystalFetch#11]
version: 1.0.1

Everything looks fine when downloading..
<img width="896" alt="image" src="https://github.com/TuringSoftware/CrystalFetch/assets/11958242/67b0902b-ddc8-490e-9253-57620b1df0b1">
<img width="899" alt="image" src="https://github.com/TuringSoftware/CrystalFetch/assets/11958242/f51f6421-20c3-40bd-8efd-933259d6865b">

after downloading process finished, some other stuff start.
<img width="910" alt="image" src="https://github.com/TuringSoftware/CrystalFetch/assets/11958242/97930e9d-6fb9-448f-a419-156b469a04e7">

And then it popup an error:
<img width="897" alt="image" src="https://github.com/TuringSoftware/CrystalFetch/assets/11958242/e7ff8056-d32d-4b63-9833-76667f2820a4">

**Comment by yswtrue** [comment]
Switch language to english solve this problem

**Comment by theggs** [comment]
This prblem has gone in the new version 2.0.0
