### ISSUE TITLE
USER_RATE_LIMITED error

### ISSUE THREAD

**Issue by kylefmohr** [TuringSoftware/CrystalFetch#12]
Hello! Just downloaded and installed v1.0.1 from the GItHub Releases, then attempted to download the latest Windows 11 Prerelease build, and received the message "Error returned from server: USER_RATE_LIMITED"

<img width="894" alt="image" src="https://github.com/TuringSoftware/CrystalFetch/assets/6644803/ad12680a-8870-427f-88e1-084b961a4652">

I additionally tried using the latest Windows 11 official build, and also attempted to download while connected to a couple of different VPN locations, but the error persists. 

Let me know if there is any other information I can provide.

**Comment by vintagedave** [comment]
Was this on the first download or after a few? I got this after download three or four different builds (trying to solve issue #5 last week.) I waited an hour and then could continue.

**Comment by kylefmohr** [comment]
It happened the very first time I used the software, from my normal, residential internet, that’s why I thought it was odd. It seems to be working normally this morning, so I’ll close the issue and chalk it up to something on either Microsoft’s or UUPDump’s end.
