### ISSUE TITLE
Edition list is garbled

### ISSUE THREAD

**Issue by wjk** [TuringSoftware/CrystalFetch#17]
As shown below.

<img width="965" alt="Screenshot 2023-08-13 at 2 26 14 PM" src="https://github.com/TuringSoftware/CrystalFetch/assets/1915951/0fa9f1c1-6573-432d-b3fb-8088333042d8">

**Comment by george-hawkins** [comment]
I came here to log the same issue.

For slightly more details, I'm using a 2022 M2 Macbook Air running Ventura 13.5.1.

And I'm using CrystalFetch v2.0.0.

If there are any more details you need, just ask

**Comment by osy** [comment]
Fixed in 7c6efa965353409b5063b68c98f91d10b4fc6cc7
