### ISSUE TITLE
Broken Windows 10 ARM64 ISO

### ISSUE THREAD

**Issue by infinitepower18** [TuringSoftware/CrystalFetch#18]
The Windows 10 ARM64 ISO output by this program doesn't work. First of all, there are too many "Windows 10" listings in the edition dropdown:

<img width="486" alt="Screenshot 2023-08-14 at 10 29 54 pm" src="https://github.com/TuringSoftware/CrystalFetch/assets/44692189/0f80e0f6-4d99-42bd-bde9-df5639999720">

Attempting to install it in UTM or VMware Fusion will just show a BSOD:

![image](https://github.com/TuringSoftware/CrystalFetch/assets/44692189/a7040456-3995-4019-a993-a7f2889f3a56)

The Windows 11 ISO output by this program doesn't seem to have this issue. Only Windows 10 for ARM64.

**Comment by BokBoy** [comment]
Morning or Afternoon to you.
I have no experience in the Crystal fetch but I can help with some things.
Firstly, System Thread Exception Not Handled means that there was an error that was not caught by a error log. This could mean a couple things.
However, I also tried this to meet the same blue screen. 
The thing I am confused about is that we cannot get a windows 10 for arm VHDX or ISO file anymore which leads me to the presumption that this may not be getting the full windows 10 iso. Even if you try UUP Dump, the servers will say that they do not have this file anymore.
My thoughts on this is that it may be that this is not the full iso and it is missing some features that lead to this.
Hopefully that clears it up but it is uncertain. Check with the owner to see if that is the reason but for now, I do not know. 
Thanks.

**Comment by osy** [comment]
This is because the version of Windows 10 that Microsoft released doesn’t support ARM64: https://docs.getutm.app/guides/windows/#installer-crashes-with-bsod-system_thread_exception_not_handled

**Comment by osy** [comment]
Added a notice in a7368fdd31309234775aa06cfcab035a7628223e
