### ISSUE TITLE
Error returned from server: UNSUPPORTED_LANG

### ISSUE THREAD

**Issue by Lakr233** [TuringSoftware/CrystalFetch#2]
```
MacBook Air
Mac14,2 - 13.5 (22G74)
Language: Simplified Chinese zh-Hans
```

<img width="1069" alt="截屏2023-07-29 09 52 30" src="https://github.com/TuringSoftware/CrystalFetch/assets/25259084/87ec024d-6d20-4470-9de5-cb363a8849cb">

**Comment by Lakr233** [comment]
Just a min I’ll fix it.

**Comment by nickperkins** [comment]
Any chance of a release with this fix?

**Comment by Lakr233** [comment]
> Any chance of a release with this fix?

Looks like you have it~
