### ISSUE TITLE
This problem has gone in the new version 2.0.0

### ISSUE THREAD

**Issue by gfourdx** [TuringSoftware/CrystalFetch#23]
This problem has gone in the new version 2.0.0

_Originally posted by @theggs in https://github.com/TuringSoftware/CrystalFetch/issues/11#issuecomment-1679340898_
            
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/68778296/265179286-3a6e0f83-4fec-4e93-903d-d8679727f950.png">

**Comment by osy** [comment]
Should be fixed by 604859d17ac75ab17c05902cc96f247127e9dc8d
