### ISSUE TITLE
Where CrystalFetch keeps ISO files after downloading them.

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [TuringSoftware/CrystalFetch#29]
Hi i just downloaded Windows 11 using CrystalFetch but I can't find the director where it downloaded file

**Comment by Kusanalee** [comment]
If you download the ISOa, it usually shows a dialogue box where it shows you where to save the file.

**Comment by hugotox** [comment]
It doesn't do anything. Clicking download again finishes super fast and no dialog is shown. Any idea where the iso could be?

**Comment by sfslowfoodie** [comment]
You may find the downloaded files in the User Library/Containers/llc.turing.CrystalFetch/Data/Library/Caches folder.

**Comment by jdlyga** [comment]
Same problem on my side.  I attempted to download windows 11 using the Mac App store version, and there was no prompt to save it to a specific location.  I did not find it in the Caches directory, and it also wasn't in downloads.  You can click download a second time and it blinks a bit, but there are no dialogs or anything.

To resolve it, I ended up removing the Mac App store version and installing it directly from the .dmg.  Then after the download finished, I was prompted to move it to the Documents directory.  It did not prompt for access to the Downloads directory, which is a bit odd.  But I was able to get it to work.

My hunch is that there's an issue with permissions.  (2.1.0 for both versions I tried).  Hope that helps!

**Comment by ingydotnet** [comment]
@jdlyga Thanks for that. 

I think you meant `~/Library/...` not `~Library/...`.

**Comment by hugo4711** [comment]
This is a usability issue. The files are being stored in the directory that I chose after downloading, but the dialog only closes without further feedback. I ended up downloading 5x after noticing that...

**Comment by dahican** [comment]
Same problem here with the Homebrew version - installing the DMG from the releases page on Github resolved it.

**Comment by jammerxd** [comment]
They aren't there in the library caches folder. I installed the dmg from github releases page and still don't have an ISO.

**Comment by raisedadead** [comment]
In a finder window you can press <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>G</kbd>, and paste the path: `~/Library/Containers/llc.turing.CrystalFetch/Data/Library/Caches`

Or in a terminal:

`cd ~/Library/Containers/llc.turing.CrystalFetch/Data/Library/Caches`

The ISOs are in the caches

<img width="1337" alt="image" src="https://github.com/TuringSoftware/CrystalFetch/assets/1884376/d0908750-0803-43a7-b240-b4ed5e5948cd">

**Comment by arjunironicss** [comment]
found it manually but the path is something like this on my Mac 
/Users/ironics/Library/Containers/llc.turing.CrystalFetch/Data/Library/Caches

**Comment by jammerxd** [comment]
It's inconsistent with when it pops up with where to save the ISO - sometimes it does eventually pop up.

**Comment by illbebach** [comment]
I propose the software make the following changes.
1. In the settings dialog, tell the user where the download is going to occur
2. Allow the user to change the download location
3. Perform the download _directory_ to that location, and not move/copy after the download.  For example, when I download the file gets put on one hard drive (which I don't want).  Only later it gets copied to the correct hard-drive, which takes extra time.

**Comment by ZeeshanAhmadKhalil** [comment]
Closing the stale issue
