### ISSUE TITLE
Always boots into UEFI shell

### ISSUE THREAD

**Issue by emizzle** [TuringSoftware/CrystalFetch#36]
Running the latest CrystalFetch 2.1.0 (4) and latest UTM 4.4.4 (92).

The first image I downloaded was Windows 10 for arm64. It downloaded fine, and I used UTM to run the image. It booted into a Windows 10 Installation screen, and I was able to click through the installation wizard up to the point of selecting the disk. When I clicked next on the select disk step, I got a BSOD. After that point, every time I try to run the image, it boots into the UEFI shell.

I tried all other flavours of images, included x64 running in emulation mode. They all boot into the UEFI Shell. Any ideas?

![screenshot](https://gcdnb.pbrd.co/images/B9REXX74t1f9.png?o=1)

**Comment by osy** [comment]
This is not an issue with CrystalFetch.
