### ISSUE TITLE
Umm Guys Windows 10 broken or smth??

### ISSUE THREAD

**Issue by BokBoy** [TuringSoftware/CrystalFetch#38]
I hope everything is explained in the picture, just ask if you need more data.
![Screenshot 2023-12-12 at 11 20 07](https://github.com/TuringSoftware/CrystalFetch/assets/132247243/bd612dce-673b-4126-b44a-fdfb49a15e4a)

FYI, this was after downloading a windows 10 ISO, and booting into the ISO lets me confirm the downloaded one was a Windows 10 one.

**Comment by osy** [comment]
Unable to reproduce

**Comment by BokBoy** [comment]
What is this, haven't been here in a while... Doesn't matter it's pretty old anyways
