### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by macuserguru** [TuringSoftware/CrystalFetch#4]
I get this Error Message with the AppStore Version:
The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

M1 MacMini, Ventura 13.5

**Comment by macuserguru** [comment]
Are Windows 11 image really ~64GB great?

**Comment by macuserguru** [comment]
Compared to your screenshot, some information is missing in my case
![CrystatlFetch](https://github.com/TuringSoftware/CrystalFetch/assets/4521744/b4069cb7-8357-4053-bab5-8d14447f05dd)
![CrystatlFetch my version](https://github.com/TuringSoftware/CrystalFetch/assets/4521744/e86f85e6-449d-4692-b097-9f0af5c11c66)

**Comment by macuserguru** [comment]
This message get I an start too - at Mac my default language are German/Austria

![CrystalFetch unsupported Language](https://github.com/TuringSoftware/CrystalFetch/assets/4521744/0a89655c-de1f-4529-a675-8a6d8d2865f0)

**Comment by eratio08** [comment]
See https://github.com/TuringSoftware/CrystalFetch/pull/3. This fix was sadly not released yet.

**Comment by motets** [comment]
> This message get I an start too - at Mac my default language are German/Austria
> 
> ![CrystalFetch unsupported Language](https://user-images.githubusercontent.com/4521744/256986974-0a89655c-de1f-4529-a675-8a6d8d2865f0.png)

If you set the primary language to US English and reboot, the apps works properly.

**Comment by osy** [comment]
Duplicate of #2
