### ISSUE TITLE
Can't download any image

### ISSUE THREAD

**Issue by bmx666** [TuringSoftware/CrystalFetch#50]
I try to get any ISO, but when the download completes, I always get this error:

<img width="1012" alt="Screenshot 2024-10-13 at 12 33 50" src="https://github.com/user-attachments/assets/df5a1d59-8e99-4701-977a-7c8d4f60aadd">

**Comment by bmx666** [comment]
nvm, if I select another language instead of English US, it works fine.

**Comment by snikch** [comment]
Same issue for me.

**Comment by duraki** [comment]
Same here - someone should take a look into this. Thanks for the hotfix tho.

cc: @osy @changanmoon

**Comment by foss-f** [comment]
Same issue
