### ISSUE TITLE
This code won’t work with recent Windows 11 builds

### ISSUE THREAD

**Issue by wjk** [TuringSoftware/CrystalFetch#8]
First of all, great idea! Unfortunately, Microsoft changed Windows so that it is impossible to create a _working_ Windows 11 ISO from a non-Windows platform any more.

I once tried using the UUP Dump scripts to create a Windows 11 ISO (for Intel, not ARM). It created an ISO as expected. However, once installed Windows was lacking critical shell components that then could not be installed by any means, resulting in a broken VM. (I could only fix the problem by wiping the VM’s disk and reinstalling using an ISO downloaded from Microsoft. However, I was using an Intel Mac at the time, which has since died the death and left me with an M1 MacBook as my only Mac. This won’t work here because there is no way to download an official Windows ARM ISO.) I filed https://github.com/uup-dump/converter/issues/42 regarding this, and [was told the following](https://github.com/uup-dump/converter/issues/42#issuecomment-1509011145):

> Store Apps are outbox since build 22563, they must be added to the installation image using Dism tool, and that's possible only on Windows host OS
> additionally, integrating updates for builds 22563+ require Windows 10 v1809 host OS

This fact makes the entire app useless unless you make a point of only retrieving builds before 22563. There should be some mention of this in the app, documentation and on the Mac App Store.

**Comment by EuroCity** [comment]
A better way to do it, now that the UUPDump method doesn’t work anymore on macOS with the most recent Windows 11 builds, could be to convert an official Microsoft ESD to an ISO, as done with this quite fast and efficient command line utility:

https://communities.vmware.com/t5/VMware-Fusion-Documents/w11arm-esd2iso-a-utility-to-create-Windows-11-ARM-ISOs-from/ta-p/2957381

Of course, with the very good CrystalFetch GUI as a frontend…

**Comment by EuroCity** [comment]
… BTW, IIRC, this is also similar to the method used by the Parallels Desktop built-in Windows 11 downloader.

**Comment by osy** [comment]
@EuroCity never knew about ESD method, thanks. Will look more into it!

**Comment by osy** [comment]
Try it out: https://github.com/TuringSoftware/CrystalFetch/releases
