### ISSUE TITLE
Escape sequences not properly removed from UI string

### ISSUE THREAD

**Issue by wjk** [TuringSoftware/CrystalFetch#9]
Consider the following screenshot.

<img width="1012" alt="Screenshot 2023-08-04 at 2 11 08 PM" src="https://github.com/TuringSoftware/CrystalFetch/assets/1915951/3fac4966-cd05-4f74-8aea-9637689a33a3">

You can see at the bottom that the status message contains `[1;94m` and `[0m` tokens. These are shell escape sequences to change the color of output text. (The leading Escape character is probably still there, too; it just doesn’t render as anything.) With all other text that appears in that field, any escape sequences that might have been there were stripped, as they should be because we’re not a terminal app. This step and the “Done” text immediately following are the only strings in the app that exhibit this bug.

**Comment by osy** [comment]
Yeah, I thought about it but I wrote this in 2 days and didn't feel like putting in the effort lol. Maybe someone else can contribute a fix...
